name: Deploy to Azure App Service

on:
  push:
    branches:
    - bradyg

env:
  AZURE_RESOURCE_GROUP_NAME: shoporleans02
  AZURE_RESOURCE_GROUP_LOCATION: eastus

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: .NET publish shopping cart app
      run: dotnet publish ./Silo/Orleans.ShoppingCart.Silo.csproj

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create resource group
      uses: azure/CLI@v1
      with:
        inlineScript: >
          echo "Creating resource group in Azure"

          az group create -l ${{ env.AZURE_RESOURCE_GROUP_LOCATION }} -n ${{ env.AZURE_RESOURCE_GROUP_NAME }}
    
    - name: Flex bicep
      run: |
        az deployment group create \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }} \
          --template-file '.github/workflows/flex/main.bicep' \
          --parameters resourceGroupLocation=${{ env.AZURE_RESOURCE_GROUP_LOCATION }} --debug

    - name: Webapp deploy
      run: |
        az webapp deploy --name "${{ env.AZURE_RESOURCE_GROUP_NAME }}silo" \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME  }} \
          --clean true --restart true \
          --type zip --src-path silo.zip --debug
