name: Deploy to Azure App Service

on:
  push:
    branches:
    - main

env:
  AZURE_RESOURCE_GROUP_NAME: orleans-resourcegroup
  AZURE_RESOURCE_GROUP_LOCATION: centralus

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: .NET publish shopping cart app
      run: dotnet publish ./Silo/Orleans.ShoppingCart.Silo.csproj

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    
    - name: Flex bicep deployment initiation
      run: |
        az deployment group create \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }} \
          --template-file '.github/workflows/flex/main.bicep' \
          --parameters name=${{ env.AZURE_RESOURCE_GROUP_NAME }} location=${{ env.AZURE_RESOURCE_GROUP_LOCATION }}

    - name: Webapp deploy
      run: |
        az webapp deploy -n "${{ env.AZURE_RESOURCE_GROUP_NAME  }}-silo" \
          -g ${{ env.AZURE_RESOURCE_GROUP_NAME  }} \
          --src-path silo.zip

